### ISSUE TITLE
reiz.reizql.compiler: Extend list-matcher

### ISSUE THREAD

**Issue by isidentical** [reizio/reiz.io#10]
Currently, the list matcher can either take a `ReizQLIgnore` or an `ReizQLMatch`, it would be awesome to have it work with `ReizQLNot` and `ReizQLLogicOperator`.
Example queries;
```
Module(body=[not Expr(Constant())])
```
```
Module(body=[Expr(Constant()) | Pass()])
```

**Comment by dmgolembiowski** [comment]
@isidentical, this project is really cool. I'd like to start collaborating with you at some point next year.

**Comment by isidentical** [comment]
> @isidentical, this project is really cool. I'd like to start collaborating with you at some point next year.

Oh, that's awesome! I actually wasn't expecting any contribution, at least not until I publicly release the project, since there are still messy parts. But I believe that `reiz.reizql` package is very safe for any additions, and from what I believe you are much more familiar with EdgeQL than me, so feel free to first open an issue and then implement any new feature to the ReizQL. 

Also, if you'd prefer a real-time alternative, I'm kind of available on discord / telegram / irc. I'd be more than happy to assist you with any questions regarding code base, design etc.
