### ISSUE TITLE
reiz.reizql: High level frontend for ReizQL

### ISSUE THREAD

**Issue by isidentical** [reizio/reiz.io#20]
This is just an idea that popped out a few times, nothing to be implemented but for mostly keeping track of things. It might be cool to have some sort of high level language (built a top on Python) to represent the queries in more human friendly manner (something like semgrep's format):
```
def ...(...): 
   for ... in ...:
       ...
   return ...
```
would ~transpile to
```
FunctionDef(
    body=[
        For(
            body=[
                ...
            ]
        ),
        Return(value = not None)
    ]
)
```

The implementation isn't as simple as people might think it is. It requires special behavior for each node type, to define what `...` represents. And also probably many different constructs to define it properly. But I would avoid starting working on this until we figure out how to implement aliases.

**Comment by isidentical** [comment]
```
FunctionDef[main] => {
    name == 'scale'
    body => [
        If,
        *...,
        Return => {
            Call => {
                value == Name(main.name)
            }
        }
    ]
}
```

**Comment by mbugrayildiz** [comment]
Might be more useful like this?

```py
def ...(...): 
    for $Name(value='i') in :FunctionCall(to=Name(value='range')):
        ...
    return $Name(value='i')
```

**Comment by isidentical** [comment]
Another example that is semantically more close to Python
```
def scale(...):
    if $expr is None:
        ***

    ***
    return ...(***, $expr)
```

that would match
```
def scale(arg1, arg2):
   if arg1 is None:
      arg1 = arg2
   print(arg1, "==>", arg1)
   print(arg2, "==>", arg2)
   return boot(1, 2, 3, arg1)
```

**Comment by isidentical** [comment]
Deferred to github.com/reizio/irun
