### ISSUE TITLE
Docker-compose version not supported

### ISSUE THREAD

**Issue by yuhc** [reizio/reiz.io#51]
I'm running Ubuntu 20.04, Docker 19.03.13, docker-compose 1.26.2.
I had to change docker-compose's version from 3.9 to 3.8 to build and start the container.

The [docker compose compatibility matrix](https://docs.docker.com/compose/compose-file/) also doesn't contain a "3.9" entry.

**Comment by isidentical** [comment]
It is indeed interesting that the matrix doesn't contain `3.9` but the examples in the same page use it; https://docs.docker.com/compose/compose-file/compose-file-v3/#build

I fixed this on the upstream, thanks for the report!
